// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOrw66o6qi2dMVYSHde6uT5MWuJtX7JXQ',
    appId: '1:1017543164770:web:5db41ebfea9cc4b9a2223b',
    messagingSenderId: '1017543164770',
    projectId: 'notificao-push-43290',
    authDomain: 'notificao-push-43290.firebaseapp.com',
    storageBucket: 'notificao-push-43290.appspot.com',
    measurementId: 'G-HCFZPCBRXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAswrb2ySq5OrdQVslEWtiXaLSPTmUsD74',
    appId: '1:1017543164770:android:299222bcf6d40103a2223b',
    messagingSenderId: '1017543164770',
    projectId: 'notificao-push-43290',
    storageBucket: 'notificao-push-43290.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz1ah60HV2xL4T4-5buHA38pxjfLq5zp4',
    appId: '1:1017543164770:ios:722f45b3a6609da0a2223b',
    messagingSenderId: '1017543164770',
    projectId: 'notificao-push-43290',
    storageBucket: 'notificao-push-43290.appspot.com',
    iosClientId: '1017543164770-gsaubvhlmlsbbvhfgv5erjmctpab6rqo.apps.googleusercontent.com',
    iosBundleId: 'com.example.notificacaoPush',
  );
}
